CHANGELOG.md
README.md
lib/src/version.dart
pubspec.yaml

- update inline documentation links and assets to be absolute

chore: bump to v0.1.1

---

README.md
example/README.md
lib/very_good_cli.dart

`pub global activate` is deprecated.
https://dart.dev/tools/pub/cmd/pub-global

docs: update pub global command

---

README.md

- docs: add pub.dev badge to README

docs: add pub.dev badge to README

---

README.md
lib/src/commands/create.dart
test/src/command_runner_test.dart

- feat: improve create command usage
```sh
🦄 A Very Good Command Line Interface
Usage: very_good <command> [arguments]
Global options:
-h, --help           Print this usage information.
--version        Print the current version.
--analytics      Toggle anonymous usage statistics.
[false]    Disable anonymous usage statistics
[true]     Enable anonymous usage statistics
Available commands:
create   very_good create <output directory>
Creates a new very good flutter project in the specified directory.
Run "very_good help <command>" for more information about a command.
```

feat: improve create command usage

---

README.md
doc/very_good_core.md

- docs: add note to use beta channel to README (closes #82)

docs: add note to use beta channel to README

---

doc/very_good_core.md

- docs(very_good_core): add flavor entry point explanation (#81)

docs(very_good_core): add flavor entry point explanation

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- improve analytics option usage ([#83](https://github.com/VeryGoodOpenSource/very_good_cli/issues/83)) ([c3ca589](https://github.com/VeryGoodOpenSource/very_good_cli/commit/c3ca589df149e2fea98f96dd5b034b14644f74ec))
- improve create command usage ([#84](https://github.com/VeryGoodOpenSource/very_good_cli/issues/84)) ([b728b21](https://github.com/VeryGoodOpenSource/very_good_cli/commit/b728b21f785db54d1b187aad02f7fad8b743bcd0))

chore: v0.1.2

---

analysis_options.yaml

- chore: remove unused excludes from analysis_options.yaml

chore: remove unused excludes from analysis_options.yaml

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.1.3

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **create:** add very good start link to cli summary ([#105](https://github.com/VeryGoodOpenSource/very_good_cli/issues/105)) ([aa06236](https://github.com/VeryGoodOpenSource/very_good_cli/commit/aa0623611cc3c1716461f9615c0864f8cd77569b))

chore: v0.1.4

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.1.5

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: bump to v0.1.6

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: bump to v0.1.7

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.1.8

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- android and web upgrades ([#129](https://github.com/VeryGoodOpenSource/very_good_cli/issues/129)) ([c4cc9dd](https://github.com/VeryGoodOpenSource/very_good_cli/commit/c4cc9ddaf31c9a33f5cfd72f5ac76fcf7e99bdcd))
- improve very good create output ([#131](https://github.com/VeryGoodOpenSource/very_good_cli/issues/131)) ([fc62b08](https://github.com/VeryGoodOpenSource/very_good_cli/commit/fc62b08162fe40a2cf03d62324ec622be6a3cdb3))
- install packages automatically ([#130](https://github.com/VeryGoodOpenSource/very_good_cli/issues/130)) ([bcff075](https://github.com/VeryGoodOpenSource/very_good_cli/commit/bcff07508457d34d222c297e0da8954cbaf32cb1))
- migrate to null safety ([#128](https://github.com/VeryGoodOpenSource/very_good_cli/issues/128)) …

chore: v0.2.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- upgrade to very_good_analysis v2.1.0 ([#133](https://github.com/VeryGoodOpenSource/very_good_cli/issues/133)) ([9e2153c](https://github.com/VeryGoodOpenSource/very_good_cli/commit/9e2153c642169eb8581710e49d4e4bc71a9b4bb1))

chore: v0.2.1

---

pubspec.yaml

- chore: use very_good_analysis v2.1.0 internally

chore: use very_good_analysis v2.1.0 internally

---

.github/workflows/very_good_cli.yaml

ci: verify pub score

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.2.2

---

.github/workflows/very_good_cli.yaml
lib/src/version.dart
pubspec.yaml

- feat: overwrite rules for file conflict resolution (closes #95)

feat: overwrite rules for file conflict resolution

---

lib/src/templates/very_good_core_bundle.dart

- feat: add recommended extensions for vscode

feat: add recommended extensions for vscode

---

.github/workflows/ci.yaml
CHANGELOG.md

- add recommended extensions for vscode ([#144](https://github.com/VeryGoodOpenSource/very_good_cli/issues/144)) ([8f162d1](https://github.com/VeryGoodOpenSource/very_good_cli/commit/8f162d131f7d4d1b724605b31638ca051dc5a8b2))
- add vscode extensions exception to gitignore ([#143](https://github.com/VeryGoodOpenSource/very_good_cli/issues/143)) ([16084f8](https://github.com/VeryGoodOpenSource/very_good_cli/commit/16084f82531782f4a9c82c1ff52ab9607b57bd78))
- overwrite rules for file conflict resolution ([#142](https://github.com/VeryGoodOpenSource/very_good_cli/issues/142)) ([87be1ca](https://github.com/VeryGoodOpenSource/very_good_cli/commit/87be1cacb702f433e3b6887115993bfc5e84df12))

chore: update CHANGELOG

---

CHANGELOG.md
README.md
lib/src/version.dart
pubspec.yaml

- support custom org name ([#148](https://github.com/VeryGoodOpenSource/very_good_cli/issues/148)) ([c0a2970](https://github.com/VeryGoodOpenSource/very_good_cli/commit/c0a2970451b03d749aa6e9845b2dd8993f2650c4))
- updated very_good_core_bundle.dart ([#149](https://github.com/VeryGoodOpenSource/very_good_cli/issues/149)) ([70507c1](https://github.com/VeryGoodOpenSource/very_good_cli/commit/70507c1b83f25641ad7d1782112e9a84eec1a8d9))

chore: v0.2.4

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- org name validation ([#151](https://github.com/VeryGoodOpenSource/very_good_cli/issues/151)) ([65c5ea6](https://github.com/VeryGoodOpenSource/very_good_cli/commit/65c5ea630c3be2169dfd8acdc61d1c29df08aec0))
- l10n non-nullable getter + variable org name segment length ([#152](https://github.com/VeryGoodOpenSource/very_good_cli/issues/152)) ([3a0cc4a](https://github.com/VeryGoodOpenSource/very_good_cli/commit/3a0cc4ac561a8e67ab42115da4bfef88770b2144))

chore: v0.2.5

---

CHANGELOG.md
README.md
lib/src/commands/create.dart
lib/src/templates/template.dart
lib/src/version.dart
pubspec.yaml
test/src/command_runner_test.dart
test/src/commands/create_test.dart

- create supports flutter and dart packages ([#154](https://github.com/VeryGoodOpenSource/very_good_cli/issues/154)) ([65605c6](https://github.com/VeryGoodOpenSource/very_good_cli/commit/65605c6b25d7b39fab4e1e025ec292eac83dc4d4))

chore: v0.3.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **create:** support custom description ([#158](https://github.com/VeryGoodOpenSource/very_good_cli/issues/158)) ([b163c49](https://github.com/VeryGoodOpenSource/very_good_cli/commit/b163c49a095aebde22370b37a6872ba54e6c16f1))

chore: v0.3.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.3.2

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- chore: v0.3.3
- **deps:** upgrade to bloc v7.1.0 and dart >=2.13.0 ([#166](https://github.com/VeryGoodOpenSource/very_good_cli/issues/166)) ([98f8724](https://github.com/VeryGoodOpenSource/very_good_cli/commit/98f87242f73b6041804d321803b5daf16dc833b1))

chore: v0.3.3

---

analysis_options.yaml
bin/very_good.dart
lib/src/command_runner.dart
lib/src/commands/create.dart
lib/src/templates/dart_package_bundle.dart
lib/src/templates/flutter_package_bundle.dart
lib/src/templates/template.dart
lib/src/templates/very_good_core_bundle.dart
pubspec.yaml
test/src/commands/create_test.dart

- refactor: use very_good_analysis v2.3.0

refactor: use very_good_analysis v2.3.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- support flutter plugin template ([#169](https://github.com/VeryGoodOpenSource/very_good_cli/issues/169)) ([82e2a1d](https://github.com/VeryGoodOpenSource/very_good_cli/commit/82e2a1d0ce1bb7ade6d1e8460d6c9d7c1052f7be))

chore: v0.4.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** upgrade to flutter_bloc v7.2.0 ([#172](https://github.com/VeryGoodOpenSource/very_good_cli/issues/172)) ([afb522d](https://github.com/VeryGoodOpenSource/very_good_cli/commit/afb522db2fe71a60d0808bc4b5e91ff2d8e834b8))

chore: v0.4.1

---

lib/src/templates/dart_package_bundle.dart
lib/src/templates/flutter_package_bundle.dart

- fix: add trailing newlines to `dart_pkg` and `flutter_pkg`

fix: add trailing newlines to dart_pkg and flutter_pkg

---

.github/workflows/very_good_cli.yaml
test/e2e_test.dart

- test: add e2e tests for dart_pkg, flutter_pkg, and core

test: add e2e tests for dart_pkg, flutter_pkg, and core

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- add trailing newlines to dart_pkg and flutter_pkg ([#183](https://github.com/VeryGoodOpenSource/very_good_cli/issues/183)) ([84c34dc](https://github.com/VeryGoodOpenSource/very_good_cli/commit/84c34dcadaf075d537bb7f89f6cbabbb8deb5a63))
- **core:** upgrade dependencies ([#185](https://github.com/VeryGoodOpenSource/very_good_cli/issues/185)) ([bdb9585](https://github.com/VeryGoodOpenSource/very_good_cli/commit/bdb9585e6d8c4a1aab1192173b1df0e9ce130fdd))

chore: v0.4.3

---

lib/src/cli/cli.dart
lib/src/cli/flutter_cli.dart
lib/src/templates/template.dart
test/src/cmd_test.dart

- refactor: modularize cli utilities
- preparation for adding a Dart CLI which supports `dart fix`

refactor: modularize cli utilities

---

pubspec.yaml

- chore(deps): upgrade to mason ^0.0.1-dev.48

chore(deps): upgrade to mason ^0.0.1-dev.48

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** template improvements ([#191](https://github.com/VeryGoodOpenSource/very_good_cli/issues/191)) ([4a405ff](https://github.com/VeryGoodOpenSource/very_good_cli/commit/4a405ffdbfd0e79238b89ca489fb54e08db91ff9))
- add auto update ([#181](https://github.com/VeryGoodOpenSource/very_good_cli/issues/181)) ([b8b490b](https://github.com/VeryGoodOpenSource/very_good_cli/commit/b8b490b288113b504e0943ed52d24138f99153a7))
- bloc v7.2.0 and internal platform updates ([#187](https://github.com/VeryGoodOpenSource/very_good_cli/issues/187)) ([193eb30](https://github.com/VeryGoodOpenSource/very_good_cli/commit/193eb304823291a5bb71a348be203bc32a1e7d77))
- run dart fix --apply as post generation step ([#189](https://github.com/VeryGoodOpenSource/very_good_cli/issues/189)) …

chore: v0.4.4

---

pubspec.yaml

- chore: upgrade to mason v0.0.1-dev.51

chore: upgrade to mason v0.0.1-dev.51

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** MainActivity.kt not found ([#197](https://github.com/VeryGoodOpenSource/very_good_cli/issues/197)) ([b450049](https://github.com/VeryGoodOpenSource/very_good_cli/commit/b450049b68dc296d3d0687694c279711baf9efa0))
- **flutter_plugin:** conditional platform support ([#195](https://github.com/VeryGoodOpenSource/very_good_cli/issues/195)) ([ea878c3](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ea878c3a8794b5f97bac956c7468464faf6712c0))

chore: v0.4.5

---

lib/src/templates/dart_package/dart_package_bundle.dart

- feat(dart_pkg): update dependencies
- very_good_analysis 2.4.0
- dart >= 2.14.0
- test: ^1.19.2

feat(dart_pkg): update dependencies

---

lib/src/templates/flutter_package/flutter_package_bundle.dart

- feat(flutter_pkg): update dependencies
- dart >= 2.14.0
- very_good_analysis 2.4.0

feat(flutter_pkg): update dependencies

---

analysis_options.yaml
lib/src/command_runner.dart
lib/src/commands/create.dart
lib/src/commands/packages.dart
lib/src/templates/flutter_package/flutter_package_template.dart
pubspec.yaml
test/e2e_test.dart
test/src/command_runner_test.dart
test/src/commands/create_test.dart
test/src/commands/packages_test.dart

- chore(deps): upgrade mason, mocktail, and very_good_analysis

chore(deps): upgrade mason, mocktail, and very_good_analysis

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.4.10

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.4.11

---

README.md

- docs: add usage examples for very_good create (closes #235)

docs: add usage examples for very_good create

---

README.md

- docs: add logo link to README

docs: add logo link to README

---

.github/workflows/very_good_cli.yaml
lib/src/command_runner.dart
lib/src/commands/create.dart
lib/src/commands/packages.dart
lib/src/templates/very_good_core/very_good_core_template.dart
pubspec.yaml
test/e2e_test.dart
test/src/command_runner_test.dart
test/src/commands/create_test.dart
test/src/commands/packages_test.dart

- refactor: upgrade to mason v0.1.0-dev.2

refactor: upgrade to mason v0.1.0-dev.2

---

.github/workflows/very_good_cli.yaml

- ci: upgrade to very_good_coverage@v1.2.0

ci: upgrade to very_good_coverage@v1.2.0

---

doc/very_good_core.md

- docs: update very_good_core.md to use latest brand assets

docs: update very_good_core.md to use latest brand assets

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml
test/src/commands/create_test.dart

- **core:** assets and bloc version updates ([#249](https://github.com/VeryGoodOpenSource/very_good_cli/issues/249)) ([a6827c6](https://github.com/VeryGoodOpenSource/very_good_cli/commit/a6827c6ad4cd2b536d855a188a07e19c245d6d79))
- **create_command:** add --org alias ([#246](https://github.com/VeryGoodOpenSource/very_good_cli/issues/246)) ([3afb420](https://github.com/VeryGoodOpenSource/very_good_cli/commit/3afb42024ada6859bc7f919da616927573412809))

chore: v0.4.12

---

pubspec.yaml

- fix: restrict mason to >=0.1.0-dev.2 <0.1.0-dev.3 (closes #255)

fix: restrict mason to >=0.1.0-dev.2 <0.1.0-dev.3

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.4.13

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- mason v0.1.0 dev.4 ([#259](https://github.com/VeryGoodOpenSource/very_good_cli/issues/259)) ([485b14c](https://github.com/VeryGoodOpenSource/very_good_cli/commit/485b14c5b4b915db50c1fca1c84385291d0d1209))

chore: v0.4.14

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.4.15

---

pubspec.yaml

- chore: use mason 0.1.0-dev.5

chore: use mason 0.1.0-dev.5

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- update prompt formatting ([#264](https://github.com/VeryGoodOpenSource/very_good_cli/issues/264)) ([f8461de](https://github.com/VeryGoodOpenSource/very_good_cli/commit/f8461dede70a318a521529a0d92a1798fea7b2c2))

chore: v0.4.16

---

lib/src/templates/flutter_plugin/flutter_plugin_bundle.dart

- fix(flutter_plugin): remove duplicate android directory (closes #267)

fix(flutter_plugin): remove duplicate android directory

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **flutter_plugin:** remove duplicate android directory ([#268](https://github.com/VeryGoodOpenSource/very_good_cli/issues/268)) ([fb61149](https://github.com/VeryGoodOpenSource/very_good_cli/commit/fb61149e0b4dfbf7c4c5b5edfb81194d82dcfde0))

chore: v0.4.17

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** upgrade to Flutter v2.10.0 ([#274](https://github.com/VeryGoodOpenSource/very_good_cli/issues/274)) ([de534e6](https://github.com/VeryGoodOpenSource/very_good_cli/commit/de534e63d934990e4e677b20e4366fe79dcd9771))

chore: v0.5.0

---

lib/src/templates/dart_package/dart_package_bundle.dart

- feat(dart_package): upgrade to Dart 2.16

feat(dart_package): upgrade to Dart 2.16

---

lib/src/templates/flutter_package/flutter_package_bundle.dart

- feat(flutter_package): upgrade to Dart 2.16

feat(flutter_package): upgrade to Dart 2.16

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **packages_get:** recursive installation ignored directories fixes ([#283](https://github.com/VeryGoodOpenSource/very_good_cli/issues/283)) ([cf9f46c](https://github.com/VeryGoodOpenSource/very_good_cli/commit/cf9f46ceb6bcceb6f159ccb47698651b01fe9396))
- **dart_package:** upgrade to Dart 2.16 ([#276](https://github.com/VeryGoodOpenSource/very_good_cli/issues/276)) ([9a880c6](https://github.com/VeryGoodOpenSource/very_good_cli/commit/9a880c69ea703072e4e3f5a5fb63c8fa2097b3d6))
- **flutter_package:** upgrade to Dart 2.16 ([#277](https://github.com/VeryGoodOpenSource/very_good_cli/issues/277)) ([f1d14c8](https://github.com/VeryGoodOpenSource/very_good_cli/commit/f1d14c80995bf8d5de6def4a12cbd640d47036bc))

chore: v0.5.1

---

README.md

- docs(README): add windows to supported platforms

docs(README): add windows to supported platforms

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** windows support ([#287](https://github.com/VeryGoodOpenSource/very_good_cli/issues/287)) ([dabb160](https://github.com/VeryGoodOpenSource/very_good_cli/commit/dabb160687d836d424e851d0d2c90487f6f41942))

chore: v0.5.2

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** android 12 builds ([#291](https://github.com/VeryGoodOpenSource/very_good_cli/issues/291)) ([ffb5946](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ffb59465db428369c6259327e9d8e303a3169a58))

chore: v0.5.3

---

lib/src/command_runner.dart
lib/src/commands/create.dart
pubspec.yaml
test/src/command_runner_test.dart
test/src/commands/create_test.dart

- refactor: upgrade to mason 0.1.0-dev.8

refactor: upgrade to mason 0.1.0-dev.8

---

pubspec.yaml

- chore(deps): upgrade to mason v0.1.0-dev.9

chore(deps): upgrade to mason v0.1.0-dev.9

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- add description variable to index.html [#297](https://github.com/VeryGoodOpenSource/very_good_cli/issues/297) ([#298](https://github.com/VeryGoodOpenSource/very_good_cli/issues/298)) ([ce88c94](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ce88c94f3f3fbfbf5d618618959969634d0143be))

chore: v0.5.4

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.5.5

---

lib/src/cli/flutter_cli.dart
test/src/cli/flutter_cli_test.dart

- fix(test): truncate output to fit line (part of #279)

fix(test): truncate output to fit line

---

CHANGELOG.md
lib/src/cli/flutter_cli.dart
lib/src/version.dart
pubspec.yaml

chore: v0.6.0-dev.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** truncate output to fit line ([#309](https://github.com/VeryGoodOpenSource/very_good_cli/issues/309)) ([5487fcf](https://github.com/VeryGoodOpenSource/very_good_cli/commit/5487fcfd3f866d5a4af008fe2276f7f2534be344))
- ignore .fvm directory ([#307](https://github.com/VeryGoodOpenSource/very_good_cli/issues/307)) ([4865a91](https://github.com/VeryGoodOpenSource/very_good_cli/commit/4865a91466a8cc62a32727fa0d1e2442cb1fb4b5))
- **test:** add --exclude-coverage flag ([#317](https://github.com/VeryGoodOpenSource/very_good_cli/issues/317)) ([8e5add0](https://github.com/VeryGoodOpenSource/very_good_cli/commit/8e5add007d116feb9c35424f2c6070452ae17462))
- **test:** add --exclude-tags option ([#314](https://github.com/VeryGoodOpenSource/very_good_cli/issues/314)) …

chore: v0.6.0

---

lib/src/commands/test/test.dart
test/src/commands/test/test_test.dart

- fix(test): run tests with `--no-pub`
When running tests without `--no-pub` if a warning is output during package installation, it is reported via stderr so the test_runner interprets it as an error and exits the process. This change always uses `--no-pub` during test execution to resolve this issue.

fix(test): run tests with --no-pub

---

lib/src/cli/flutter_cli.dart
test/src/cli/flutter_cli_test.dart

- feat(test): remove .test_runner.dart after run

feat(test): remove .test_runner.dart after run

---

README.md
lib/src/commands/test/test.dart
test/src/commands/test/test_test.dart

- feat(test): add --no-optimization flag

feat(test): add --no-optimization flag

---

lib/src/cli/flutter_cli.dart
lib/src/commands/test/templates/test_runner_bundle.dart
test/src/cli/flutter_cli_test.dart

- fix(test): test_runner runs tests in isolated groups (closes #320)

fix(test): test_runner runs tests in isolated groups

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** run tests with --no-pub ([#322](https://github.com/VeryGoodOpenSource/very_good_cli/issues/322)) ([005c2aa](https://github.com/VeryGoodOpenSource/very_good_cli/commit/005c2aa1ad6537ce2c6ac215fd1e4d97b3f1e68c))
- **test:** test_runner runs tests in isolated groups ([#329](https://github.com/VeryGoodOpenSource/very_good_cli/issues/329)) ([5d01936](https://github.com/VeryGoodOpenSource/very_good_cli/commit/5d0193693266adcf4cc3fdd90251e2c7a7b62c67))
- **test:** add --no-optimization flag ([#325](https://github.com/VeryGoodOpenSource/very_good_cli/issues/325)) ([fae2a6d](https://github.com/VeryGoodOpenSource/very_good_cli/commit/fae2a6d012f955924611fba0d8b24f28c966ad31))
- **test:** add --test-randomize-ordering-seed ([#326](https://github.com/VeryGoodOpenSource/very_good_cli/issues …

chore: v0.6.1

---

lib/src/cli/flutter_cli.dart
test/src/cli/flutter_cli_test.dart

- fix(test): resolve range error when truncating due to whitespace

fix(test): resolve range error when truncating due to whitespace

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.6.2

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** flutter_test compatibility ([#337](https://github.com/VeryGoodOpenSource/very_good_cli/issues/337)) ([844a599](https://github.com/VeryGoodOpenSource/very_good_cli/commit/844a5993a509ef5a4404d0e52b1f4e88c7a75701))

chore: v0.6.3

---

lib/src/cli/flutter_cli.dart
lib/src/commands/test/test.dart
test/src/cli/flutter_cli_test.dart
test/src/commands/test/test_test.dart

- fix(test): output random seed when specified (closes #335)
```sh
$ very_good test --test-randomize-ordering-seed random        
Shuffling test order with --test-randomize-ordering-seed=4033303807
Running "flutter test" in my_app...
✓ Optimizing tests (1.5s)
```

fix(test): output random seed when specified

---

README.md
lib/src/commands/test/test.dart
test/src/commands/test/test_test.dart

- feat(test): add --update-goldens (closes #339)

feat(test): add --update-goldens

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** output random seed when specified ([#340](https://github.com/VeryGoodOpenSource/very_good_cli/issues/340)) ([edcd171](https://github.com/VeryGoodOpenSource/very_good_cli/commit/edcd17127771f325d3b14bbdfdf207985daf1859))
- **test:** add --update-goldens ([#341](https://github.com/VeryGoodOpenSource/very_good_cli/issues/341)) ([6483d0a](https://github.com/VeryGoodOpenSource/very_good_cli/commit/6483d0aba2bd338f95c6e8d9335f9886e4aaf767))

chore: v0.6.4

---

lib/src/cli/flutter_cli.dart
test/src/cli/flutter_cli_test.dart

- fix(test): cleanup .test_runner.dart on failure (closes #346)

fix(test): cleanup .test_runner.dart on failure

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml
test/src/cli/flutter_cli_test.dart

- **test:** cleanup .test_runner.dart on failure ([#348](https://github.com/VeryGoodOpenSource/very_good_cli/issues/348)) ([548e872](https://github.com/VeryGoodOpenSource/very_good_cli/commit/548e8724e1490e7ceac846053cde562b9dfc50c8))
- **test:** exit (non-zero) on test failure ([#344](https://github.com/VeryGoodOpenSource/very_good_cli/issues/344)) ([828fb51](https://github.com/VeryGoodOpenSource/very_good_cli/commit/828fb51cffeab917f156bdf8cf119912eb60fdf1))

chore: v0.6.5

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** `.test_runner.dart` has invalid import path on windows ([#349](https://github.com/VeryGoodOpenSource/very_good_cli/issues/349)) ([6be8220](https://github.com/VeryGoodOpenSource/very_good_cli/commit/6be822016e5bb105272fa6e144647f90de80087d))

chore: v0.6.6

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** bump lcov file creation timeout ([#358](https://github.com/VeryGoodOpenSource/very_good_cli/issues/358)) ([78bc4f5](https://github.com/VeryGoodOpenSource/very_good_cli/commit/78bc4f5de6a73beb3f3537896e48bd148863d6fe))
- description is being escaped ([#357](https://github.com/VeryGoodOpenSource/very_good_cli/issues/357)) ([9c5293b](https://github.com/VeryGoodOpenSource/very_good_cli/commit/9c5293b545f8b911a37ff5cb95c33b302b1bf356))

chore: v0.6.7

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** upgrade to gradle 7.1.2 ([#365](https://github.com/VeryGoodOpenSource/very_good_cli/issues/365)) ([ecef487](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ecef48798ea758b64bfef9e52bd041de001be14e))

chore: v0.6.9

---

lib/src/cli/flutter_cli.dart
pubspec.yaml
test/src/cli/flutter_cli_test.dart

- fix(test): coverage timeout (closes #371)

fix(test): coverage timeout

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** coverage timeout ([#375](https://github.com/VeryGoodOpenSource/very_good_cli/issues/375)) ([78d549e](https://github.com/VeryGoodOpenSource/very_good_cli/commit/78d549ebb34064ffda1620d243223b0b2340c1c5))

chore: v0.6.10

---

lib/src/cli/cli.dart
lib/src/cli/flutter_cli.dart
lib/src/cli/git_cli.dart
pubspec.yaml
test/src/cli/flutter_cli_test.dart
test/src/cli/git_cli_test.dart

- feat(packages): ensure git dependencies are reachable (closes #372)

feat(packages): ensure git dependencies are reachable

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **packages:** ensure git dependencies are reachable ([#379](https://github.com/VeryGoodOpenSource/very_good_cli/issues/379)) ([886bb85](https://github.com/VeryGoodOpenSource/very_good_cli/commit/886bb8561a3865845613a19e54b5e342c9866384))
- **test:** imply --coverage when --min-coverage is supplied ([#367](https://github.com/VeryGoodOpenSource/very_good_cli/issues/367)) ([666b513](https://github.com/VeryGoodOpenSource/very_good_cli/commit/666b5130968ab3816809682047502e1422a03225))

chore: v0.6.11

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- update to mocktail ^0.3.0 ([#384](https://github.com/VeryGoodOpenSource/very_good_cli/issues/384)) ([3c3a45b](https://github.com/VeryGoodOpenSource/very_good_cli/commit/3c3a45b0c1ffcd73fa2359456ba81d62c3e440c2))
- **core:** upgrade to Flutter 2.10.5 ([#382](https://github.com/VeryGoodOpenSource/very_good_cli/issues/382)) ([1d7576e](https://github.com/VeryGoodOpenSource/very_good_cli/commit/1d7576e059b18782e12609dd83d9b548ade55aa2))

chore: v0.6.12

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- ### Features
- upgrade to Flutter 3.0.0 and Dart 2.17.0 ([#390](https://github.com/VeryGoodOpenSource/very_good_cli/issues/390)) ([b092c7f](https://github.com/VeryGoodOpenSource/very_good_cli/commit/b092c7f18ceeeae78a1fd5c65045fe36a637df7c))

chore: v0.7.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.7.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- upgrade templates to very_good_analysis ^3.0.0 ([#398](https://github.com/VeryGoodOpenSource/very_good_cli/issues/398)) ([4a4fb8d](https://github.com/VeryGoodOpenSource/very_good_cli/commit/4a4fb8dca65a12c6639f59f4c16f9e48c8815be9))

chore: v0.7.2

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** add trailing newline when no test folder found ([#405](https://github.com/VeryGoodOpenSource/very_good_cli/issues/405)) ([ca37274](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ca3727472b27ceef724798ba33af015718577897))
- **test:** allow packages without a test directory ([#404](https://github.com/VeryGoodOpenSource/very_good_cli/issues/404)) ([3ece759](https://github.com/VeryGoodOpenSource/very_good_cli/commit/3ece759eb07e442b7bd02c20275c9cf1a19ee8de))
- **test:** list failing tests ([#397](https://github.com/VeryGoodOpenSource/very_good_cli/issues/397)) ([d229c5e](https://github.com/VeryGoodOpenSource/very_good_cli/commit/d229c5eb60a26d3a64e633eac471f86dfcdbe594))

chore: v0.7.3

---

pubspec.yaml

- fix: lock mason_logger version to <0.1.0-dev.9

fix: lock mason_logger version to <0.1.0-dev.9

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.7.4

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **test:** support --concurrency option ([#416](https://github.com/VeryGoodOpenSource/very_good_cli/issues/416)) ([42697e4](https://github.com/VeryGoodOpenSource/very_good_cli/commit/42697e4ee1c839675e229319541d9aa5d30203e0))
- show command usage on exception ([#414](https://github.com/VeryGoodOpenSource/very_good_cli/issues/414)) ([1523dcb](https://github.com/VeryGoodOpenSource/very_good_cli/commit/1523dcbdc681ff65df1e1d28ba5a130aadb14ee7))

chore: v0.7.5

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **create:** run pre-gen hooks ([#436](https://github.com/VeryGoodOpenSource/very_good_cli/issues/436)) ([75b5f65](https://github.com/VeryGoodOpenSource/very_good_cli/commit/75b5f65d834f93d02b8023162acaf2807d210525))
- **create:** add Dart CLI template ([#431](https://github.com/VeryGoodOpenSource/very_good_cli/issues/431)) ([1c3a5f0](https://github.com/VeryGoodOpenSource/very_good_cli/commit/1c3a5f01d708a76aa88388d6ba69e4c3a917f132))
- upgrade to mason_logger ^0.1.0-dev.12 ([#434](https://github.com/VeryGoodOpenSource/very_good_cli/issues/434)) ([f85da74](https://github.com/VeryGoodOpenSource/very_good_cli/commit/f85da7400fd6456c781756a48b501af250192a6d))

chore: v0.7.8

---

lib/src/cli/cli.dart
test/src/cli/dart_cli_test.dart
test/src/cli/process_overrides_test.dart

- refactor(dart_cli): stub process.run in unit tests (part of #380)

refactor(dart_cli): stub process.run in unit tests

---

test/src/cli/flutter_cli_test.dart

- refactor(flutter_cli): stub process.run in unit tests (part of #380)

refactor(flutter_cli): stub process.run in unit tests

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- **core:** upgrade to Flutter 3.0.4 ([#454](https://github.com/VeryGoodOpenSource/very_good_cli/issues/454)) ([1ff2764](https://github.com/VeryGoodOpenSource/very_good_cli/commit/1ff2764baf6ff9d687c4c7807e35939fe1ffb4d1))

chore: v0.7.10

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

- `flutter_plugin` template generates all platforms no matter the platform flag used ([#462](https://github.com/VeryGoodOpenSource/very_good_cli/issues/462)) ([29c034e](https://github.com/VeryGoodOpenSource/very_good_cli/commit/29c034e77748b5a0dff267cdeedb18d280df510c))
- move alert messages to custom method ([#461](https://github.com/VeryGoodOpenSource/very_good_cli/issues/461)) ([ec31ed9](https://github.com/VeryGoodOpenSource/very_good_cli/commit/ec31ed9ec24966bbc0596fe0e359041a406328ee))
- **flutter_plugin:** remove static workflows ([#456](https://github.com/VeryGoodOpenSource/very_good_cli/issues/456)) ([fc41f17](https://github.com/VeryGoodOpenSource/very_good_cli/commit/fc41f17aa760573aaf8b36c57d216ce5b7cdf0c5))
- **flutter_plugin:** generate copyright header dates via pregen hook …

chore: v0.7.11

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.7.13

---

README.md
lib/src/command_runner.dart
lib/very_good_cli.dart
pubspec.yaml
test/src/command_runner_test.dart

- chore: standardize on command-line naming

chore: standardize on command-line naming

---

pubspec.yaml

Refactor: update pubspec "homepage" to "repository"

refactor: update pubspec "homepage" to "repository" 

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.0

---

README.md

- docs: fix create usage in README

docs: fix create usage in README

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.2

---

.github/CODEOWNERS

docs: switch codeowners

---

pubspec.yaml

- fix: only animate stdout progress on terminals

fix: only animate stdout progress on terminals

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.3

---

site/docs/templates/dart_cli.md
site/docs/templates/dart_pkg.md
site/docs/templates/docs_site.md
site/docs/templates/federated_plugin.md
site/docs/templates/flame_game.md
site/docs/templates/flutter_pkg.md

docs: add game template

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.4

---

README.md

- docs: add flame_game to README

docs: add flame_game to README

---

site/docs/templates/flame_game.md

docs: update flame game info

---

site/src/pages/index.tsx

docs: update blogs on home

---

README.md

- Simplify README
- Add link to docs site 🚀

docs: simply README

---

site/docs/resources/tutorials.md

add Flame game blog to list of tutorials

docs: add Flame game blog to tutorials

---

site/docs/resources/tutorials.md

fix typo (start -> starter) how did i not notice this before lol

docs: fix typo

---

site/docs/resources/tutorials.md

docs: update plugin blurb

---

site/docs/templates/core.md
site/docs/templates/docs_site.md
site/docs/templates/federated_plugin.md
site/src/pages/index.tsx

- flip order of fed plugins and docs site on sidebar
- add link to flutter create counter app
- add link for flame game to pillar on home page

docs: update copy

---

site/package-lock.json
site/package.json

- chore(deps): upgrade to docusaurus 2.2.0

chore(deps): upgrade to docusaurus 2.2.0

---

README.md
site/docs/templates/docs_site.md

- docs: minor improvements to docs site documentation

docs: minor improvements to docs site documentation

---

site/docs/templates/docs_site.md

docs(docs site): update copy

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.8.6

---

CHANGELOG.md

chore: v0.9.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.9.1

---

test/e2e_test.dart

Ensure we are using a proper temp directory for running our e2e tests

test: use a proper temp directory for the e2e tests

---

lib/src/commands/create/commands/commands.dart
lib/src/commands/create/commands/flutter_plugin.dart
lib/src/commands/create/create.dart
test/src/commands/create/commands/flutter_plugin_test.dart
test/src/commands/create/commands/legacy_test.dart
test/src/commands/create/create_test.dart

feat: create flutter plugin new usage

---

.github/workflows/very_good_cli.yaml
lib/src/commands/create/commands/commands.dart
lib/src/commands/create/commands/flame_game.dart
lib/src/commands/create/create.dart
test/src/commands/create/commands/flame_game_test.dart
test/src/commands/create/commands/legacy_test.dart
test/src/commands/create/create_test.dart
test/src/commands/create/e2e/flame_game/flame_game_test.dart

feat: create flame game new usage

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.10.0

---

lib/src/commands/create/commands/docs_site.dart
test/src/commands/create/commands/docs_site_test.dart

- fix(create): docs site template org validation (closes #615)

fix(create): docs site template org validation

---

.github/workflows/bump_templates.yaml

ci: add bump templates workflow
Automate prs like #637

ci: add bump templates workflow

---

.github/workflows/bump_templates.yaml

ci: fix update templates workflow

ci: fix update templates workflow

---

.github/workflows/bump_templates.yaml

fix: bump_templates.yaml

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.11.0

---

CHANGELOG.md
README.md
lib/src/version.dart
pubspec.yaml

chore: fix readme so it looks good on pub.dev

chore: v0.11.0+1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.12.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.12.1

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.12.2

---

test/src/commands/create/e2e/flame_game/flame_game_test.dart

Increase the timeout from 2 minutes to 5 minutes to avoid test timeouts (https://github.com/VeryGoodOpenSource/very_good_cli/actions/runs/4489850285/jobs/7896191072) failing the CI.

test: increase flame_game_test e2e timeout

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.12.3

---

CHANGELOG.md
pubspec.yaml

chore: re-relase to fix readme file on pub. (not changing here because the change is not permanent)

chore: v0.12.3+1

---

lib/src/version.dart
test/fixtures/async_main/pubspec.yaml
test/helpers/expect_successful_process_result.dart
test/helpers/helpers.dart
test/src/commands/create/e2e/dart_cli/dart_cli_test.dart
test/src/commands/create/e2e/dart_package/dart_pkg_test.dart
test/src/commands/create/e2e/docs_site/docs_site_test.dart
test/src/commands/create/e2e/flame_game/flame_game_test.dart
test/src/commands/create/e2e/flutter_app/core_test.dart
test/src/commands/create/e2e/flutter_package/flutter_pkg_test.dart
test/src/commands/create/e2e/flutter_plugin/flutter_plugin_test.dart
test/src/commands/create/e2e/legacy/core_test.dart
test/src/commands/create/e2e/legacy/dart_cli_test.dart
test/src/commands/create/e2e/legacy/dart_pkg_test.dart
test/src/commands/create/e2e/legacy/docs_site_test.dart
test/src/commands/create/e2e/legacy/flame_game_test.dart
test/src/commands/create/e2e/legacy/flutter_pkg_test.dart
test/src/commands/test/e2e/async_main_test.dart
test/src/commands/test/e2e/no_project_test.dart

Refactor e2e tests and fix some issues:
- don't run `flutter test` on non-flutter templates. See: https://github.com/dart-lang/test/issues/1977
- run `very_good test` e2e tests with the correct working directory, which is used by the command internally.
- improve test failure messages for unsuccessful process results.

test: refactor e2e tests

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.13.0

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.13.1

---

CONTRIBUTING.md

docs(CONTRIBUTING): quick grammar change

---

.github/workflows/very_good_cli.yaml
CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.14.0

---

.github/workflows/e2e.yaml
.github/workflows/very_good_cli.yaml
e2e/test/commands/test/compilation_error/compilation_error_test.dart
e2e/test/commands/test/compilation_error/fixture/analysis_options.yaml
e2e/test/commands/test/compilation_error/fixture/lib/compilation_error.dart
e2e/test/commands/test/compilation_error/fixture/pubspec.yaml
e2e/test/commands/test/compilation_error/fixture/test/src/my_package_test.dart
lib/src/cli/flutter_cli.dart
test/fixtures/test_runner_fixtures.dart
test/src/cli/flutter_cli_test.dart

fix: dont crash on test compilation error 
fixes #727

fix: dont crash on test compilation error

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.15.0

---

site/docusaurus.config.js
site/src/css/custom.css

standardize nav bar to align with workflows

docs: standardize nav bar with other docs sites

---

.github/workflows/e2e.yaml

Temporary removes the failing flame game from e2e tests.
cc: @wolfenrain

ci: removed flame game from ci tests

---

site/docusaurus.config.js
site/src/css/custom.css

Update navbar styling so that it matches other docs sites (workflows; DF coming next)

docs: standardize navbar styling

---

site/docusaurus.config.js

simplify footer/match other docs sites

docs: simplify footer

---

site/docusaurus.config.js
site/src/css/custom.css

docs: update theming to match dart frog night mode

---

.github/CODEOWNERS

chore: request codeowner to erickzanardo

---

pubspec.yaml

chore: update pubspec meta info

chore: update pubspec meta info

---

.github/workflows/test_optimizer.yaml
bricks/test_optimizer/brick.yaml
bricks/test_optimizer/hooks/pubspec.yaml
e2e/pubspec.yaml
e2e/test/commands/test/async_main/fixture/pubspec.yaml
e2e/test/commands/test/compilation_error/fixture/pubspec.yaml
lib/src/commands/test/templates/test_optimizer_bundle.dart
test/src/commands/create/create_test.dart
test/src/commands/packages_test.dart

chore: update dependencies and SDK constraints on sub packages and fixtures

chore: update dependencies and SDK constraints on sub packages and fixtures

---

.github/workflows/e2e.yaml

build: run e2e tests on latest version of flutter

build: run e2e tests on latest version of flutter

---

README.md
site/docs/overview.md
site/docs/resources/tutorials.md

Update some punctual outdated information on the docs site and readme

docs: update docs

---

package-lock.json

chore: remove extraneous lock file

chore: remove extraneous lock file

---

tool/spdx_license/__brick__/spdx_license.gen.dart
tool/spdx_license/test/spdx_license.gen.dart

See original contribution https://github.com/VeryGoodOpenSource/very_good_cli/pull/817#discussion_r1342664362

refactor: reduced new objects when parsing SpdxLicense

---

.github/workflows/bump_templates.yaml

Change related to https://github.com/VeryGoodOpenSource/very_good_cli/pull/835#discussion_r1345816619

ci: deffer reviewers to codeowners on bump_templates

---

lib/src/commands/packages/commands/check/commands/licenses.dart
test/src/commands/packages/commands/check/commands/licenses_test.dart

Updates the progress completion message to include the count of dependencies per license.
https://github.com/VeryGoodOpenSource/very_good_cli/assets/44524995/f5e448f8-85be-46d0-84c5-69b9a8944d4f

feat: include license count upon `check licenses` progress completion

---

README.md
site/docs/overview.md

docs: add path setup instructions

---

lib/src/commands/packages/commands/check/check.dart
lib/src/commands/packages/commands/check/commands/licenses.dart
test/src/commands/packages/commands/check/check_test.dart
test/src/commands/packages/commands/check/commands/licenses_test.dart
test/src/commands/packages/packages_test.dart

Shows `check licenses` command.

feat: show `check licenses` command

---

site/docs/overview.md

**READY**
Markdown had no reference to the link.

docs: add missing path_setup_link

---

.github/workflows/e2e.yaml

**READY**
Very Good Flame Game Template is broken in the latest Flutter version. Disabling this so the pipeline can be green.
https://github.com/VeryGoodOpenSource/very_good_flame_game/issues/132

ci: disable flame_game e2e test

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.18.0

---

site/docs/commands/check_licenses.md

**READY**
Fixed link format in `check_licenses.md`

docs: fix check_licenses.md pana link

---

.github/workflows/site.yaml
site/.github/workflows/main.yaml

**READY**
Bump node version for actions. Should have been done as part of #907 but got missed

chore: bump node version for actions

---

pubspec.yaml
test/src/commands/packages/commands/check/commands/licenses_test.dart

**READY**
Resolves #901 
Adds a temporary override until the following issue is resolved https://github.com/alexei-sintotski/pubspec_lock/issues/33

fix: avoid failing with 'direct overridden' dependencies

---

site/docs/commands/check_licenses.md

> Should be merged after #931 and just before the next release
**READY**
Documents the changes made by #931 
Somewhat related to #901

docs: include 'direct-overridden' in check licenses

---

.github/labels.yaml
.github/workflows/sync_labels.yaml

**READY**
Adds windows label to categorise those issues that are windows specific.

chore: add windows label

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

**READY**
Prepares 0.22.0 release, see the CHANGELOG.md for release details.

chore: v0.22.0

---

CONTRIBUTING.md

**READY**
Fixes #1068 by updating the URL's to the templates.

docs: update links to templates in Contributing

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

**READY**
Prepares v0.22.1 release. Changes in CHANGELOG.md.

chore: v0.22.1

---

.github/workflows/pub_publish.yaml
CHANGELOG.md
lib/src/version.dart
pubspec.yaml

**READY**
Related to https://github.com/VeryGoodOpenSource/_very_good_chores/issues/128.
Changes in CHANGELOG.

chore: v0.22.2

---

.github/workflows/pub_publish.yaml

**READY**
Removes dry run step, see failure https://github.com/VeryGoodOpenSource/very_good_cli/actions/runs/10181435292/job/28161581282.

ci: remove dry run from pub_publish

---

.github/workflows/e2e.yaml
.github/workflows/very_good_cli.yaml
pubspec.yaml

chore: tighten dependencies

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

chore: v0.23.1

---

site/docusaurus.config.js

**READY**
Fixes #1196. Updating docs site to point to new VGV Dev page.

docs: update vgv dev URL

---

CHANGELOG.md
lib/src/version.dart
pubspec.yaml

**READY**
Prepare release of very_good_cli 0.26.0.

chore: v0.26.0

---

.github/workflows/release_please.yaml
.github/workflows/very_good_cli.yaml

**READY**
- having only negative patterns blocks the workflow to run.

fix: release workflow trigger

---

.github/workflows/site_deploy.yaml

**READY**
- fix(site): upgrade node version due to build issues.

fix(site): node version
