VeryGoodOpenSource/very_good_cli

- README.md
- lib/src/command_runner.dart
- test/src/command_runner_test.dart
- feat: improve analytics option usage (closes #80)
```sh
🦄 A Very Good Command Line Interface
Usage: very_good <command> [arguments]
Global options:
-h, --help           Print this usage information.
--version        Print the current version.
--analytics      Toggle anonymous usage statistics.
[false]    Disable anonymous usage statistics
[true]     Enable anonymous usage statistics
Available commands:
create   Creates a new very good flutter application in seconds.
Run "very_good help <command>" for more information about a command.
```
Running `very_good --analytics` will return a less noisy error:
```sh
$ very_good --analytics
Missing argument for "analytics".
🦄 A Very Good Command Line Interface
Usage: very_good <command> [arguments]
Global options:
-h, --help           Print this …
```
> feat: improve analytics option usage

- lib/src/commands/create.dart
- test/src/commands/create_test.dart
- feat: improve very good create output
- test: improve tests for create command logging output
> feat: improve very good create output

- lib/src/commands/create.dart
- test/src/commands/create_test.dart
Modified CLI to support additional argument for a custom organization name.
> feat: support custom org name

- lib/src/commands/create.dart
- test/src/commands/create_test.dart
When trying to use the new `--org-name` support I found that underscores were not being supported. After looking a little closer, the regex for the org name was incorrect by not enforcing that segments must start with a letter and by enforcing a min/max of three segments.
I updated the org name regex, invalid org error message, and added more tests for edge cases.
- [Android rules](https://developer.android.com/studio/build/application-id)
- [iOS rules](https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier#discussion)
- [Flutter android validation](https://github.com/flutter/flutter/blob/76d5e62f42dffe3aba42bba9364c4469af1ff332/packages/flutter_tools/lib/src/commands/create_base.dart#L481)
> fix: org name validation

- .github/workflows/very_good_cli.yaml
- dart_test.yaml
- lib/src/cli/cli.dart
- lib/src/cli/dart_cli.dart
- lib/src/cli/flutter_cli.dart
- lib/src/templates/template.dart
- test/e2e_test.dart
- test/src/cli/dart_cli_test.dart
- test/src/cli/flutter_cli_test.dart
- test/src/commands/create_test.dart
- feat: run dart fix --apply as post generation step
> feat: run dart fix --apply as post generation step

- README.md
- lib/src/commands/create.dart
- test/src/commands/create_test.dart
- feat(create_command): add --org alias (closes #243)
> feat(create_command): add --org alias

- lib/src/command_runner.dart
- lib/src/version.dart
- test/src/command_runner_test.dart
- fix: update prompt formatting
> fix: update prompt formatting

- lib/src/cli/cli.dart
- test/src/commands/packages_test.dart
- fix(packages_get): recursive installation ignored directories fixes
> fix(packages_get): recursive installation ignored directories fixes

- lib/src/cli/cli.dart
- test/src/commands/packages_test.dart
Add `.fvm` to ignored directories to avoid `packages get --recursive` command being run for all packages inside `.fvm` folder.
Fixes: #306
> fix: add .fvm to ignored directories for pubspec files searching

- README.md
- lib/src/cli/cli.dart
- lib/src/cli/flutter_cli.dart
- lib/src/commands/test.dart
- pubspec.yaml
- test/src/cli/flutter_cli_test.dart
- test/src/commands/test_test.dart
Adds the `--coverage` and `--min-coverage` options to the `test` command
Part of #279
> feat(test): add `--coverage` and `--min coverage` options

- README.md
- lib/src/cli/flutter_cli.dart
- lib/src/commands/test.dart
- test/src/commands/test_test.dart
- feat(test): support specific test execution
> feat(test): support specific test execution

- README.md
- lib/src/commands/test.dart
- test/src/commands/test_test.dart
- feat(test): add --exclude-tags option
> feat(test): add --exclude-tags option

- .github/workflows/very_good_cli.yaml
- lib/src/cli/cli.dart
- lib/src/cli/flutter_cli.dart
- lib/src/commands/commands.dart
- lib/src/commands/create/create.dart
- lib/src/commands/test/templates/test_runner_bundle.dart
- lib/src/commands/test/test.dart
- pubspec.yaml
- test/src/cli/flutter_cli_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/test/test_test.dart
- feat(test): performance optimizations (part of #279)
> feat(test): performance optimizations

- README.md
- lib/src/commands/test/test.dart
- test/src/commands/test/test_test.dart
- feat(test): add --test-randomize-ordering-seed
> feat(test): add --test-randomize-ordering-seed

- lib/src/cli/cli.dart
- lib/src/cli/flutter_cli.dart
- lib/src/commands/test/test.dart
- test/src/cli/flutter_cli_test.dart
- test/src/commands/test/test_test.dart
- fix(test): exit (non-zero) on test failure
> fix(test): exit (non-zero) on test failure

- .github/workflows/very_good_cli.yaml
- lib/src/cli/flutter_cli.dart
- test/src/cli/flutter_cli_test.dart
- fix(test): report errors/warnings without throwing (closes #392)
> fix(test): report errors without throwing

- lib/src/cli/cli.dart
- lib/src/cli/flutter_cli.dart
- pubspec.yaml
- test/src/cli/flutter_cli_test.dart
Adds a listing of failing tests after a test run as proposed on #377
> feat(#377): list failing tests

- lib/src/cli/flutter_cli.dart
- test/src/cli/flutter_cli_test.dart
Check if there is a `test` directory before calling the `flutter test`.
Proposal to fix the #373
> fix(373): check if there is a test directory before run flutter test

- lib/src/commands/create/create.dart
- test/src/commands/create/create_test.dart
- fix(create): run pre-gen hooks
> fix(create): run pre-gen hooks

- test/src/cli/git_cli_test.dart
- refactor(git_cli): stub process.run in unit tests (part of #380)
> refactor(git_cli): stub process.run in unit tests

- lib/src/command_runner.dart
- test/src/command_runner_test.dart
- feat: enhance upgrade prompt to use very_good update
> feat: enhance upgrade prompt to use very_good update

- lib/src/commands/create/templates/dart_package/dart_package_template.dart
- lib/src/commands/create/templates/flutter_package/flutter_package_template.dart
- lib/src/commands/create/templates/flutter_plugin/flutter_plugin_template.dart
- lib/src/commands/create/templates/very_good_core/very_good_core_template.dart
- lib/src/commands/create/templates/very_good_dart_cli/very_good_dart_cli_template.dart
- lib/src/logger_extension.dart
- test/src/commands/create/create_test.dart
After talking with @renancaraujo and @felangel we came to the conclusion that we were abusing the alert message, it is meant to indicate something severe or a call to action but we mostly used it for the pretty colors.
Fixing that by moving to a custom message that uses these pretty colors.
> fix: move alert messages to custom method

- README.md
As explained on #504 [here](https://github.com/VeryGoodOpenSource/very_good_cli/issues/504#issuecomment-1273872050), we enforce `--no-pub` by design.
This PR adds a brief section on the README explaining about that.
> docs: adding docs about --no-pub

- lib/src/command_runner.dart
- lib/src/commands/update.dart
- test/src/command_runner_test.dart
fix: update prompt on update
fix: https://github.com/VeryGoodOpenSource/very_good_cli/issues/520
fix: https://github.com/VeryGoodOpenSource/very_good_cli/issues/521
> fix: update prompt on update

- site/docs/overview.md
Both the application id and publishable arguments from the create command were missing in the site docs.
> docs: adding missing arguments on the create docs

- lib/src/command_runner.dart
- pubspec.yaml
- test/src/command_runner_test.dart
Adds the completion package to add bash completion
Closes #590
> feat: add completion

- .github/workflows/very_good_cli.yaml
- lib/src/commands/create/commands/commands.dart
- lib/src/commands/create/commands/create_subcommand.dart
- lib/src/commands/create/commands/dart_package.dart
- lib/src/commands/create/create.dart
- test/src/commands/create/commands/dart_package_test.dart
- test/src/commands/create/commands/legacy_test.dart
- test/src/commands/create/create_subcommand_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/create/e2e/dart_package/dart_pkg_test.dart
> feat: create dart package new usage

- .github/workflows/very_good_cli.yaml
- lib/src/commands/create/commands/commands.dart
- lib/src/commands/create/commands/dart_cli.dart
- lib/src/commands/create/create.dart
- test/src/commands/create/commands/dart_cli_test.dart
- test/src/commands/create/commands/legacy_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/create/e2e/dart_cli/dart_cli_test.dart
> feat: create dart cli new usage

- .github/workflows/very_good_cli.yaml
- lib/src/commands/create/commands/commands.dart
- lib/src/commands/create/commands/docs_site.dart
- lib/src/commands/create/create.dart
- test/src/commands/create/commands/docs_site_test.dart
- test/src/commands/create/commands/legacy_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/create/e2e/docs_site/docs_site_test.dart
> feat: create docs site new usage

- .github/workflows/very_good_cli.yaml
- lib/src/commands/commands.dart
- lib/src/commands/create/commands/commands.dart
- lib/src/commands/create/commands/create_subcommand.dart
- lib/src/commands/create/commands/flutter_package.dart
- lib/src/commands/create/create.dart
- test/src/commands/create/commands/flutter_package_test.dart
- test/src/commands/create/commands/legacy_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/create/e2e/flutter_package/flutter_pkg_test.dart
> feat: create flutter package new usage

- README.md
- lib/src/commands/create/commands/dart_cli.dart
- lib/src/commands/create/commands/dart_package.dart
- lib/src/commands/create/commands/docs_site.dart
- lib/src/commands/create/commands/flame_game.dart
- lib/src/commands/create/commands/flutter_app.dart
- lib/src/commands/create/commands/flutter_package.dart
- lib/src/commands/create/commands/flutter_plugin.dart
- lib/src/commands/create/templates/very_good_dart_package/very_good_dart_package_template.dart
- lib/src/commands/create/templates/very_good_flutter_package/very_good_flutter_package_template.dart
- lib/src/commands/create/templates/very_good_flutter_plugin/very_good_flutter_plugin_template.dart
- site/docs/overview.md
- site/docs/resources/syntax_changes_in_0_10_0.md
- test/src/commands/create/commands/dart_cli_test.dart
- test/src/commands/create/commands/dart_package_test.dart
- test/src/commands/create/commands/docs_site_test.dart
- test/src/commands/create/commands/flame_game_test.dart
- test/src/commands/create/commands/flutter_app_test.dart
- test/src/commands/create/commands/flutter_package_test.dart
- test/src/commands/create/commands/flutter_plugin_test.dart
- test/src/commands/create/commands/legacy_test.dart
- test/src/commands/create/create_test.dart
Addresses this comment: https://github.com/VeryGoodOpenSource/very_good_cli/pull/621#discussion_r1071544602
> feat: change description of create sub commands

- lib/src/cli/flutter_cli.dart
- lib/src/commands/test/test.dart
- test/src/cli/flutter_cli_test.dart
- test/src/commands/test/test_test.dart
The aim of this PR is to allow force ansi output even the output isn't tty. This option is helpful for CI like gitlab CI or other CI tools that support ansi output. This allows more readable log particularly the final report.
Code tested with Gitlab-CI. 
- Without ansi-output
- With ansi-output
> feat: Allow force ansi output to enhance log readibility

- .github/workflows/test_optimizer.yaml
- bricks/test_optimizer/hooks/pubspec.yaml
- lib/src/commands/test/templates/test_optimizer_bundle.dart
The `test_optimizer` brick hooks have a higher dart constraint than the CLI itself, meaning our users can no longer run tests using the CLI when they are on 2.18.
> fix(test_optimizer): set dart constraint to v2.18.0

- .github/workflows/test_optimizer.yaml
- bricks/test_optimizer/hooks/analysis_options.yaml
- bricks/test_optimizer/hooks/pubspec.yaml
- lib/src/commands/test/templates/test_optimizer_bundle.dart
fix(test_optimizer): mismatch of versions on hook
> fix(test_optimizer): mismatch of versions on hook

- site/docs/commands/get_pkgs.md
- site/docs/commands/test.md
Update docs for changes made on #640
> docs(site): update commands docs

- lib/src/commands/create/commands/flutter_plugin.dart
- test/src/commands/create/commands/flutter_plugin_test.dart
Fixes: https://github.com/VeryGoodOpenSource/very_good_cli/issues/747
Partially fixes: https://github.com/VeryGoodOpenSource/very_good_flutter_plugin/issues/128
> fix: pass `org_name` to the plugin template

- tool/release_ready.sh
chore: add release ready script
> chore: add release ready script

- README.md
Some users might want to rollback their Very Good CLI to a specific version. Although the usage is common through all packages this knowledge is not widely spread and hence this could help some users.
> docs: document specific version install

- .github/workflows/very_good_cli.yaml
- CONTRIBUTING.md
- test/src/cli/flutter_cli_test.dart
> fix: avoid failure when running local tests

- CONTRIBUTING.md
I've corrected the markdown formatting in the CONTRIBUTING.md file to improve readability and usability. The mistake was related to the markdown link syntax.
Specific Changes:
- Corrected the formatting of the link to compatible Flutter SDK versions.
- Replaced inline code formatting with a standard link format.
- Ensured that the URL in the link is correctly formatted.
These changes make the document more user-friendly and help users access the linked resource without confusion.
> fix: markdown formatting correction in CONTRIBUTING.md file

- bricks/spdx_license/__brick__/spdx_license.gen.dart
Adds a `tryParse` method to validate future CLI user inputs when white/black listing certain licenses. `unknown` will be a valid license type but erroneous input (for example, `MIP` instead of `MIT`) should throw an exception for a better user experience.
Changes:
- Modified `parse` to throw a FormatException when failed to parse (similar to int.parse)
- Included `tryParse` to return null if can't be parsed (similar to int.tryParse)
> feat(spdx_license): include tryParse

- lib/src/commands/packages/commands/check/commands/licenses.dart
- test/src/commands/packages/commands/check/commands/licenses_test.dart
Renames `ignore-failures` to `ignore-retrieval-failures` since it causes some confusion, see[ @erickzanardo comment.](https://github.com/VeryGoodOpenSource/very_good_cli/pull/846#discussion_r1355623819)
> feat: rename `ignore-failures` to `ignore-retrieval-failures`

- lib/src/commands/packages/commands/check/commands/licenses.dart
- test/src/commands/packages/commands/check/commands/licenses_test.dart
Updates the help message for forbidden and allowed options.
The usage of "blacklist" and "whitelist" is discouraged by [Google's developer word list](https://developers.google.com/style/word-list#blacklist).
(cc: @KyleFin)
> docs: update forbidden and allowed options help message

- lib/src/commands/packages/commands/check/commands/licenses.dart
- test/src/commands/packages/commands/check/commands/licenses_test.dart
Ignores empty allow or forbidden.
**After**
```sh
very_good packages check licenses --allowed="" --forbidden="" 
very_good packages check licenses --allowed="MIT" --forbidden="" 
very_good packages check licenses --allowed="" --forbidden="MIT" 
```
**Before**
```sh
very_good packages check licenses --allowed="" --forbidden="" 
very_good packages check licenses --allowed="MIT" --forbidden="" 
very_good packages check licenses --allowed="" --forbidden="MIT" 
```
> fix: ignore empty allowed or forbidden

- lib/src/logger_extension.dart
- test/src/command_runner_test.dart
- test/src/logger_extension_test.dart
> fix: avoid failure when terminal has no columns

- README.md
- lib/src/commands/packages/commands/check/commands/licenses.dart
- site/docs/overview.md
- test/src/commands/packages/commands/check/check_test.dart
- test/src/commands/packages/commands/check/commands/licenses_test.dart
Adds license checking documentation to README section.
Changes:
- Adds license checking to README
- Adds licence checking to documentation overview 
- Fixed documentation typo in command description
- Adds links to commands that references in README the docs site
> docs: add license checking documentation to commands' overview

- CHANGELOG.md
- lib/src/version.dart
- pubspec.yaml
All the changes associated are automatically generated by: 
```sh
tool/release_ready.sh 0.17.1
```
See CHANGELOG for details.
> chore: v0.17.1

- test/src/commands/packages/commands/check/commands/licenses_test.dart
**READY**
Small refactor that removed the redundant tempDirectory initialization.
> test: reuse tempDirectory in setUp

- .github/workflows/e2e.yaml
- e2e/test/commands/packages/check/licenses/licenses_allowed_test.dart
- e2e/test/commands/packages/check/licenses/licenses_forbidden_test.dart
**READY**
Adds some e2e test for `packages check licenses`.
> test(e2e): add e2e test for licenses check

- .github/workflows/e2e.yaml
- e2e/test/commands/create/flame_game/flame_game_test.dart
**READY**
Removes commented flame_game e2e test since the blocking issue is closed.
> ci(e2e): re-enable flame_game e2e test

- tool/generate_bundles.sh
**READY**
Updates the "generate_bundles.sh" script to only format bundles. This avoids the "bump_templates.yaml" bundle to terminate unnecessarily.
> fix: update generate_bundles.sh to only format bundles

- lib/src/cli/flutter_cli.dart
- test/src/cli/flutter_cli_test.dart
Fixes: #754
**READY**
The change introduced in this PR is to clean up the console when the cwd is printed. Specifically when running `very_good test`.
Sometimes the full path of the cwd is too long and would be cut off. If running recursively, this can leave the developer confused as to which directory was tested.
A solution to the problem is to shorten the path printed to console. Instead of printing the absolute path, the relative path is used.
> refactor: Use relative path instead of absolute when running `test`

- e2e/pubspec.yaml
- lib/src/commands/packages/commands/check/commands/licenses.dart
- lib/src/pubspec_lock/pubspec_lock.dart
- pubspec.yaml
- test/src/commands/packages/commands/check/commands/licenses_test.dart
- test/src/pubspec_lock/pubspec_lock_test.dart
> Should be merged after #930 
**READY**
Adds support for "direct-overriden" dependency type on `very_good packages check licenses --dependency-type 'direct-overridden`.
Had to abandon the use of `pubspec_lock` since the dependency seems to not be maintained any more and overriding it caused the pana score to drop.
Somewhat related to #901
> feat: support 'direct-overridden' dependency type when checking licenses

- lib/src/cli/dart_cli.dart
- lib/src/cli/flutter_cli.dart
- lib/src/cli/git_cli.dart
- lib/src/commands/create/templates/post_generate_actions.dart
- lib/src/commands/create/templates/very_good_core/very_good_core_template.dart
- lib/src/commands/create/templates/very_good_dart_cli/very_good_dart_cli_template.dart
- lib/src/commands/create/templates/very_good_dart_package/very_good_dart_package_template.dart
- lib/src/commands/create/templates/very_good_flame_game/very_good_flame_game_template.dart
- lib/src/commands/create/templates/very_good_flutter_package/very_good_flutter_package_template.dart
- lib/src/commands/create/templates/very_good_flutter_plugin/very_good_flutter_plugin_template.dart
- lib/src/commands/create/templates/very_good_wear_app/very_good_wear_app_template.dart
- lib/src/commands/packages/commands/get.dart
- lib/src/pub_license/spdx_license.gen.dart
- test/src/cli/dart_cli_test.dart
- test/src/cli/flutter_cli_test.dart
- test/src/commands/packages/commands/get_test.dart
**READY**
This PR does not fix #987 but does mitigate the potential of it happening as much as possible
> fix: flutter_gen breaks current template

- .github/workflows/e2e.yaml
- .github/workflows/very_good_cli.yaml
- lib/src/cli/flutter_cli.dart
- lib/src/commands/create/commands/create_subcommand.dart
**READY**
Related to #1045
Changes:
- Updates workflows to use Flutter 3.22
- Updates the use of wildcards to avoid dropping pana score, and hence failing the CI
> ci: update workflows to use Flutter 3.22

- .github/workflows/spdx_license.yaml
- .github/workflows/test_optimizer.yaml
- bricks/test_optimizer/hooks/pubspec.yaml
- e2e/pubspec.yaml
- e2e/test/commands/test/async_main/fixture/pubspec.yaml
- e2e/test/commands/test/compilation_error/fixture/pubspec.yaml
- lib/src/commands/test/templates/test_optimizer_bundle.dart
- pubspec.yaml
- test/src/commands/create/commands/dart_cli_test.dart
- test/src/commands/create/commands/dart_package_test.dart
- test/src/commands/create/commands/docs_site_test.dart
- test/src/commands/create/commands/flame_game_test.dart
- test/src/commands/create/commands/flutter_app_test.dart
- test/src/commands/create/commands/flutter_package_test.dart
- test/src/commands/create/commands/flutter_plugin_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/packages/commands/get_test.dart
- tool/spdx_license/hooks/pubspec.yaml
- tool/spdx_license/pubspec.yaml
**READY**
Related to #1045 
Changes:
- Updates Very Good CLI min dart SDK to be Dart 3.4 (since all its templates now rely on Dart 3.4)
- Updates internal packages in the ecosystem (bricks and tooling packages) to use Dart 3.4 so that all versions are homogeneous and the available new features are readily available for development
- Updates test fixtures to use Dart 3.4
> feat!: update package and ecosystem to Dart 3.4

- site/docs/commands/test.md
**READY**
Resolves [#972](https://github.com/VeryGoodOpenSource/very_good_cli/issues/972)
> docs: add Golden Test documentation for very_good test command

- lib/src/commands/test/test.dart
- test/src/commands/test/test_test.dart
**READY**
On our project we had one line uncovered, which gave us a coverage of 99.995%. Our minimum coverage is 100%. The message given was `Expected coverage >= 100.00% but actual is 100.00%`, which isn't very helpful. This change will still use 2 decimal places unless the actual coverage is so close that it rounds to the expected amount, and in that case will increase to an appropriate number of decimal places.
> fix: show a better message when coverage is really close to min coverage

- lib/src/command_runner.dart
- test/src/command_runner_test.dart
**READY**
Marketing team is making some path changes on the website and asked for this change. Current URL is still working and redirecting to the new one for a period of time so nothing is broken but need to get this deployed soon so they can take down the old route.
> chore: update subscribe URL

- CHANGELOG.md
- lib/src/version.dart
- pubspec.yaml
**READY**
Closes #1207. Creates v0.25.0 release.
Note: deps-dev and site related PR's have been removed from the changelog
> chore: v0.25.0

- .github/workflows/release_please.yaml
- site/docs/overview.md
- site/docs/templates/core.md
- site/docs/templates/dart_cli.md
- site/docs/templates/dart_pkg.md
- site/docs/templates/docs_site.md
- site/docs/templates/federated_plugin.md
- site/docs/templates/flame_game.md
- site/docs/templates/flutter_pkg.md
- site/docs/templates/wear.md
**READY/IN DEVELOPMENT/HOLD**
- docs: create command updates
- ignore site docs updates for releases
- related to #996
> docs(site): create command updates

- .github/workflows/bump_templates.yaml
- .github/workflows/e2e.yaml
- .github/workflows/pub_publish.yaml
- .github/workflows/spdx_license.yaml
- .github/workflows/spdx_license_bot.yaml
- .github/workflows/test_optimizer.yaml
- .github/workflows/very_good_cli.yaml
- bricks/test_optimizer/hooks/pubspec.yaml
- e2e/pubspec.yaml
- e2e/test/commands/test/async_main/fixture/pubspec.yaml
- e2e/test/commands/test/compilation_error/fixture/pubspec.yaml
- e2e/test/commands/test/spaced_golden_file_name/fixture/pubspec.yaml
- pubspec.yaml
- test/src/commands/create/commands/dart_cli_test.dart
- test/src/commands/create/commands/dart_package_test.dart
- test/src/commands/create/commands/docs_site_test.dart
- test/src/commands/create/commands/flame_game_test.dart
- test/src/commands/create/commands/flutter_app_test.dart
- test/src/commands/create/commands/flutter_package_test.dart
- test/src/commands/create/commands/flutter_plugin_test.dart
- test/src/commands/create/create_test.dart
- test/src/commands/packages/commands/get_test.dart
- tool/spdx_license/hooks/pubspec.yaml
- tool/spdx_license/pubspec.yaml
**IN DEVELOPMENT**
Bumps Dart to 3.9.0 and Flutter to 3.35.0.
> feat: upgrade to flutter 3.35.0

- lib/src/cli/dart_cli.dart
- lib/src/cli/test_cli_runner.dart
- lib/src/commands/dart/commands/dart_test_command.dart
- test/src/commands/dart/commands/dart_test_test.dart
**READY**
Adds the `report-on` flag to the `very_good dart test` command. This will enable very good cli to be used in projects which the source folder is not always on the `lib` folder. (e.g. Dart Frog projects).
The same flag was not added to `very_good test` since the flutter test command will always report on the lib folder as that is hardcoded in their code.
> feat: Adding report-on flag to the dart test command

- .github/workflows/e2e.yaml
- e2e/helpers/command_helper.dart
- e2e/test/commands/create/dart_cli/dart_cli_test.dart
- e2e/test/commands/create/dart_package/dart_pkg_test.dart
- e2e/test/commands/create/docs_site/docs_site_test.dart
- e2e/test/commands/create/flame_game/flame_game_test.dart
- e2e/test/commands/create/flutter_app/core_test.dart
- e2e/test/commands/create/flutter_package/flutter_pkg_test.dart
- e2e/test/commands/create/flutter_plugin/flutter_plugin_test.dart
- e2e/test/commands/packages/check/licenses/licenses_allowed_test.dart
- e2e/test/commands/packages/check/licenses/licenses_forbidden_test.dart
- e2e/test/commands/packages/check/licenses/unknown_licenses_test.dart
- e2e/test/commands/test/async_main/async_main_test.dart
- e2e/test/commands/test/compilation_error/compilation_error_test.dart
- e2e/test/commands/test/no_project/no_project_test.dart
- e2e/test/commands/test/spaced_golden_file_name/spaced_golden_file_name_test.dart
- lib/src/commands/packages/commands/check/commands/licenses.dart
- test/src/commands/packages/commands/check/commands/licenses_test.dart
> fix: report malformed licenses as unknown
